apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::509307198497:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H343FPYK4M9U
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::509307198497:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-24T14:08:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "908"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f088691f-e36a-4025-8c77-480c94c389f9
